server:
                        port: 80

                        spring:
                          application:
                            name: cloud-consumerzk-order
                          cloud:
                            zookeeper:
                              connect-string: 192.168.2.101:2181